local M = {}

M.vscode_kind = {
  Text = "  ",
  Method = "  ",
  Function = "  ",
  Constructor = "  ",
  Field = "  ",
  Variable = "  ",
  Class = "  ",
  Interface = "  ",
  Module = "  ",
  Property = "  ",
  Unit = "  ",
  Value = "  ",
  Enum = "  ",
  Keyword = "  ",
  Snippet = "  ",
  Color = "  ",
  File = "  ",
  Reference = "  ",
  Folder = "  ",
  EnumMember = "  ",
  Constant = "  ",
  Struct = "  ",
  Event = "  ",
  Operator = "  ",
  TypeParameter = "  ",
  Copilot = "  ",
  Codeium = "  ",
}

M.kind_abbrev = {
  Text = "Txt",
  Method = "Mtd",
  Function = "Func",
  Constructor = "Ctor",
  Field = "Field",
  Variable = "Var",
  Class = "Cls",
  Interface = "Intf",
  Module = "Mod",
  Property = "Prop",
  Unit = "Unit",
  Value = "Val",
  Enum = "Enum",
  Keyword = "Keyw",
  Snippet = "Snp",
  Color = "Colr",
  File = "File",
  Reference = "Ref",
  Folder = "Fldr",
  EnumMember = "EnumMbr",
  Constant = "Const",
  Struct = "Strct",
  Event = "Evt",
  Operator = "Opr",
  TypeParameter = "Type",
  Copilot = "AI",
  Codeium = "AI",
}

return M
