local M = {}

M.vscode_kind = {
  Text = "  ",
  Method = "  ",
  Function = "  ",
  Constructor = "  ",
  Field = "  ",
  Variable = "  ",
  Class = "  ",
  Interface = "  ",
  Module = "  ",
  Property = "  ",
  Unit = "  ",
  Value = "  ",
  Enum = "  ",
  Keyword = "  ",
  Snippet = "  ",
  Color = "󱓻 ",
  File = "  ",
  Reference = "  ",
  Folder = "  ",
  EnumMember = "  ",
  Constant = "  ",
  Struct = "  ",
  Event = "  ",
  Operator = "  ",
  TypeParameter = "  ",
  Copilot = "  ",
  Codeium = "  ",
}

M.kind_abbrev = {
  Text = "Text",
  Method = "Method",
  Function = "Function",
  Constructor = "Constructor",
  Field = "Field",
  Variable = "Variable",
  Class = "Class",
  Interface = "Interface",
  Module = "Module",
  Property = "Property",
  Unit = "Unit",
  Value = "Value",
  Enum = "Enum",
  Keyword = "Keyword",
  Snippet = "Snippet",
  Color = "Color",
  File = "File",
  Reference = "Reference",
  Folder = "Folder",
  EnumMember = "Enum Member",
  Constant = "Constant",
  Struct = "Struct",
  Event = "Event",
  Operator = "Operator",
  TypeParameter = "Type",
  Copilot = "AI",
  Codeium = "AI",
}

return M
